# Dependencies
markdown:         redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables"]
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            XOS Guide
tagline:          'XOS Guide'
description:      'A guide to using, developing, and\break operating XOS'
url:              http://open-cloud.github.io
baseurl:          /

author:
  name:           'open-cloud'
  url:            https://github.com/open-cloud

paginate:         5

# Custom vars
version:          0.0.1

github:
  repo:           https://github.com/open-cloud/open-cloud.github.io
